//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerFolder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerFolder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerFolder Outlook Add-In.
        /// </summary>
        internal static string application_title {
            get {
                return ResourceManager.GetString("application_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your did not enter your credentials.
        ///Please do that to save the preferences..
        /// </summary>
        internal static string config_credentials_empty {
            get {
                return ResourceManager.GetString("config_credentials_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preferences are empty. Please enter your credentials and server address..
        /// </summary>
        internal static string config_empty {
            get {
                return ResourceManager.GetString("config_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and server to use the password recovery..
        /// </summary>
        internal static string config_password_recovery {
            get {
                return ResourceManager.GetString("config_password_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dialogImage {
            get {
                object obj = ResourceManager.GetObject("dialogImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number for the maximum download count of the file link..
        /// </summary>
        internal static string filelink_error_maxDownload {
            get {
                return ResourceManager.GetString("filelink_error_maxDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number for the validity of the file link..
        /// </summary>
        internal static string filelink_error_validity {
            get {
                return ResourceManager.GetString("filelink_error_validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to connect to the selected server..
        /// </summary>
        internal static string http_connect_failure {
            get {
                return ResourceManager.GetString("http_connect_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to create a connection to the server..
        /// </summary>
        internal static string http_timeout {
            get {
                return ResourceManager.GetString("http_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to authenticate the entered user.
        ///Please check your credentials..
        /// </summary>
        internal static string http_unauthorized {
            get {
                return ResourceManager.GetString("http_unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon48x48 {
            get {
                object obj = ResourceManager.GetObject("Icon48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon48x481 {
            get {
                object obj = ResourceManager.GetObject("Icon48x481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to send the E-Mail due to missing quota on your account..
        /// </summary>
        internal static string mail_quota_exceeded {
            get {
                return ResourceManager.GetString("mail_quota_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch31506\stshfloch31506\stshfhich31506\stshfbi31507\deflang1031\deflangfe1031\themelang1031\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}
        ///{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PowerFolder_Software_license {
            get {
                return ResourceManager.GetString("PowerFolder_Software_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pref_header {
            get {
                object obj = ResourceManager.GetObject("pref_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsIconsOutlook {
            get {
                object obj = ResourceManager.GetObject("SettingsIconsOutlook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available. Would you like to download it now?.
        /// </summary>
        internal static string update_new_version {
            get {
                return ResourceManager.GetString("update_new_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerfolder is up to date..
        /// </summary>
        internal static string update_up_to_date {
            get {
                return ResourceManager.GetString("update_up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updateIconOutlook {
            get {
                object obj = ResourceManager.GetObject("updateIconOutlook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
